import 'package:flutter/material.dart';
import 'package:flutterapp/optica2020app/generatedimagendepropiedadwidget2/generated/GeneratedRectangle10Widget2.dart';
import 'package:flutterapp/optica2020app/generatedimagendepropiedadwidget2/generated/GeneratedCopyWidget5.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Component Imagen de propiedad
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImagendepropiedadWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 414.0,
      height: 349.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 349.0,
              child: GeneratedRectangle10Widget2(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.03864734299516908;

                final double height =
                    constraints.maxHeight * 0.045845272206303724;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.05555555555555555,
                      y: constraints.maxHeight * 0.8080229226361032,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedCopyWidget5(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
