import 'package:flutter/material.dart';
import 'package:flutterapp/optica2020app/generatedpropiedadwidget1/generated/Generated31663167Widget4.dart';
import 'package:flutterapp/optica2020app/generatedpropiedadwidget1/generated/Generated\$550Widget4.dart';
import 'package:flutterapp/optica2020app/generatedpropiedadwidget1/generated/GeneratedRectangle7Widget2.dart';
import 'package:flutterapp/optica2020app/generatedpropiedadwidget1/generated/GeneratedCrystalWidget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/optica2020app/generatedpropiedadwidget1/generated/GeneratedRectangle8Widget2.dart';
import 'package:flutterapp/optica2020app/generatedpropiedadwidget1/generated/GeneratedFrame4Widget2.dart';
import 'package:flutterapp/optica2020app/generatedpropiedadwidget1/generated/GeneratedCopyWidget4.dart';
import 'package:flutterapp/optica2020app/generatedpropiedadwidget1/generated/GeneratedRectangle5Widget3.dart';

/* Component Propiedad
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPropiedadWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 380.0,
      height: 200.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height = constraints.maxHeight;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRectangle5Widget3(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 380.0,
              height: 200.0,
              child: GeneratedRectangle7Widget2(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 380.0,
              height: 200.0,
              child: GeneratedRectangle8Widget2(),
            ),
            Positioned(
              left: 20.0,
              top: 9.0,
              right: null,
              bottom: null,
              width: 107.0,
              height: 23.0,
              child: GeneratedFrame4Widget2(),
            ),
            Positioned(
              left: 17.0,
              top: 151.0,
              right: null,
              bottom: null,
              width: 82.0,
              height: 28.0,
              child: GeneratedCrystalWidget4(),
            ),
            Positioned(
              left: 22.0,
              top: 178.0,
              right: null,
              bottom: null,
              width: 16.0,
              height: 16.0,
              child: GeneratedCopyWidget4(),
            ),
            Positioned(
              left: 302.0,
              top: 164.0,
              right: null,
              bottom: null,
              width: 60.0,
              height: 31.0,
              child: Generated$550Widget4(),
            ),
            Positioned(
              left: 42.0,
              top: 179.0,
              right: null,
              bottom: null,
              width: 71.0,
              height: 16.0,
              child: Generated31663167Widget4(),
            )
          ]),
    ));
  }
}
