import 'package:flutter/material.dart';
import 'package:flutterapp/optica2020app/generatedframe6widget/generated/GeneratedPencilsharpWidget1.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/optica2020app/generatedframe6widget/generated/GeneratedEliminarpropiedadWidget.dart';
import 'package:flutterapp/optica2020app/generatedframe6widget/generated/GeneratedEditarpropiedadWidget.dart';
import 'package:flutterapp/optica2020app/generatedframe6widget/generated/GeneratedClosecircleWidget.dart';

/* Component Frame 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(12, 0, 0, 0),
                  offset: Offset(0.0, 4.0),
                  blurRadius: 4.0,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(20.0),
        child: Container(
          width: 150.0,
          height: 70.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(20.0),
            border: Border.all(
              width: 0.5,
              color: Color.fromARGB(255, 130, 130, 130),
            ),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(20.0),
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 28.0,
                  top: 16.0,
                  right: null,
                  bottom: null,
                  width: 103.0,
                  height: 19.0,
                  child: GeneratedEditarpropiedadWidget(),
                ),
                Positioned(
                  left: 30.0,
                  top: 39.0,
                  right: null,
                  bottom: null,
                  width: 113.0,
                  height: 16.0,
                  child: GeneratedEliminarpropiedadWidget(),
                ),
                Positioned(
                  left: 10.0,
                  top: 13.0,
                  right: null,
                  bottom: null,
                  width: 20.0,
                  height: 20.0,
                  child: GeneratedPencilsharpWidget1(),
                ),
                Positioned(
                  left: 10.0,
                  top: 36.0,
                  right: null,
                  bottom: null,
                  width: 20.0,
                  height: 20.0,
                  child: GeneratedClosecircleWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
