import 'package:flutter/material.dart';

/* Frame play
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPlayWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 19.0,
        height: 18.962303161621094,
      ),
    ));
  }
}
