import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/optica2020app/generatedeyeoutlinewidget/generated/GeneratedVectorWidget4.dart';
import 'package:flutterapp/optica2020app/generatedeyeoutlinewidget/generated/GeneratedVectorWidget5.dart';

/* Frame eye-outline
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEyeoutlineWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 512.0,
          height: 512.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.8750370144844055;
                    double scaleX = (constraints.maxWidth * percentWidth) /
                        448.0189514160156;

                    double percentHeight = 0.5625;
                    double scaleY =
                        (constraints.maxHeight * percentHeight) / 288.0;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX:
                              constraints.maxWidth * 0.06249813362956047,
                          translateY: constraints.maxHeight * 0.21875,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget4())
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.3125;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 160.0;

                    double percentHeight = 0.3125;
                    double scaleY =
                        (constraints.maxHeight * percentHeight) / 160.0;

                    return Stack(children: [
                      TransformHelper.translateAndScale(
                          translateX: constraints.maxWidth * 0.34375,
                          translateY: constraints.maxHeight * 0.34375,
                          translateZ: 0,
                          scaleX: scaleX,
                          scaleY: scaleY,
                          scaleZ: 1,
                          child: GeneratedVectorWidget5())
                    ]);
                  }),
                )
              ]),
        ),
      ),
    ));
  }
}
