import 'package:flutter/material.dart';
import 'package:flutterapp/optica2020app/generateddetalleswidget1/generated/GeneratedMenuinferiorWidget4.dart';
import 'package:flutterapp/optica2020app/generateddetalleswidget1/generated/GeneratedDetallesdelapropiedadWidget1.dart';
import 'package:flutterapp/optica2020app/generateddetalleswidget1/generated/GeneratedImagendepropiedadWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/optica2020app/generateddetalleswidget1/generated/GeneratedRectangle5Widget2.dart';
import 'package:flutterapp/optica2020app/generateddetalleswidget1/generated/GeneratedMenusuperiorWidget1.dart';

/* Frame Detalles
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDetallesWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 240, 240, 240),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.37388392857142855;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.004464285714285714,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle5Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 806.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 90.0,
                child: GeneratedMenuinferiorWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 349.0,
                child: GeneratedImagendepropiedadWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 110.0,
                child: GeneratedMenusuperiorWidget1(),
              ),
              Positioned(
                left: 14.0,
                top: 302.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 430.0,
                child: GeneratedDetallesdelapropiedadWidget1(),
              )
            ]),
      ),
    ));
  }
}
