import 'package:flutter/material.dart';
import 'package:flutterapp/optica2020app/generatedperfilwidget12/generated/GeneratedMenusuoeriorWidget3.dart';
import 'package:flutterapp/optica2020app/generatedperfilwidget12/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/optica2020app/generatedperfilwidget12/generated/GeneratedMispropiedadesWidget2.dart';
import 'package:flutterapp/optica2020app/generatedperfilwidget12/generated/GeneratedPortadaWidget.dart';
import 'package:flutterapp/optica2020app/generatedperfilwidget12/generated/GeneratedDeyraJimenezWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/optica2020app/generatedperfilwidget12/generated/GeneratedMispropiedadesWidget1.dart';
import 'package:flutterapp/optica2020app/generatedperfilwidget12/generated/GeneratedMispropiedadesWidget.dart';
import 'package:flutterapp/optica2020app/generatedperfilwidget12/generated/GeneratedEditarWidget.dart';
import 'package:flutterapp/optica2020app/generatedperfilwidget12/generated/GeneratedUsuarioVerificadoWidget.dart';
import 'package:flutterapp/optica2020app/generatedperfilwidget12/generated/GeneratedMenuinferiorWidget6.dart';
import 'package:flutterapp/optica2020app/generatedperfilwidget12/generated/GeneratedVectorWidget197.dart';
import 'package:flutterapp/optica2020app/generatedperfilwidget12/generated/GeneratedBotonWidget5.dart';

/* Frame Perfil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPerfilWidget12 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 240, 240, 240),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 806.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 90.0,
                child: GeneratedMenuinferiorWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 110.0,
                child: GeneratedMenusuoeriorWidget3(),
              ),
              Positioned(
                left: 17.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 450.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 14.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 449.0,
                child: GeneratedPortadaWidget(),
              ),
              Positioned(
                left: 141.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 154.0,
                height: 28.0,
                child: GeneratedDeyraJimenezWidget(),
              ),
              Positioned(
                left: 167.0,
                top: 335.0,
                right: null,
                bottom: null,
                width: 103.0,
                height: 16.0,
                child: GeneratedUsuarioVerificadoWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.04906400966183575;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 20.3125;

                  double percentHeight = 0.022670200892857144;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 20.3125;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.34057971014492755,
                        translateY: constraints.maxHeight * 0.3705357142857143,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget197())
                  ]);
                }),
              ),
              Positioned(
                left: 330.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedEditarWidget(),
              ),
              Positioned(
                left: 91.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 253.0,
                height: 60.0,
                child: GeneratedMispropiedadesWidget(),
              ),
              Positioned(
                left: 91.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 253.0,
                height: 60.0,
                child: GeneratedMispropiedadesWidget1(),
              ),
              Positioned(
                left: 91.0,
                top: 552.0,
                right: null,
                bottom: null,
                width: 253.0,
                height: 60.0,
                child: GeneratedMispropiedadesWidget2(),
              ),
              Positioned(
                left: 37.0,
                top: 655.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedBotonWidget5(),
              )
            ]),
      ),
    ));
  }
}
