import 'package:flutter/material.dart';
import 'package:flutterapp/optica2020app/generatedajusteswidget14/generated/GeneratedGroup15Widget.dart';
import 'package:flutterapp/optica2020app/generatedajusteswidget14/generated/GeneratedMenuinferiorWidget7.dart';
import 'package:flutterapp/optica2020app/generatedajusteswidget14/generated/GeneratedGroup13Widget.dart';
import 'package:flutterapp/optica2020app/generatedajusteswidget14/generated/GeneratedConfiguratuspreferenciasWidget.dart';
import 'package:flutterapp/optica2020app/generatedajusteswidget14/generated/GeneratedBotonWidget6.dart';
import 'package:flutterapp/optica2020app/generatedajusteswidget14/generated/GeneratedGroup14Widget.dart';
import 'package:flutterapp/optica2020app/generatedajusteswidget14/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/optica2020app/generatedajusteswidget14/generated/GeneratedMenusuoeriorWidget4.dart';
import 'package:flutterapp/optica2020app/generatedajusteswidget14/generated/GeneratedGroup11Widget.dart';
import 'package:flutterapp/optica2020app/generatedajusteswidget14/generated/GeneratedGroup12Widget.dart';
import 'package:flutterapp/optica2020app/generatedajusteswidget14/generated/GeneratedLoscambiosquerealicesseveranreflejadosautomaticamenteWi.dart';

/* Frame Ajustes
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAjustesWidget14 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 240, 240, 240),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 806.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 90.0,
                child: GeneratedMenuinferiorWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 110.0,
                child: GeneratedMenusuoeriorWidget4(),
              ),
              Positioned(
                left: 17.0,
                top: 138.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 620.0,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 28.0,
                child: GeneratedConfiguratuspreferenciasWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 201.0,
                right: null,
                bottom: null,
                width: 361.0,
                height: 30.0,
                child:
                    GeneratedLoscambiosquerealicesseveranreflejadosautomaticamenteWi(),
              ),
              Positioned(
                left: 31.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 49.0,
                child: GeneratedGroup11Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 49.0,
                child: GeneratedGroup12Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 49.0,
                child: GeneratedGroup13Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 489.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 49.0,
                child: GeneratedGroup14Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 559.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 49.0,
                child: GeneratedGroup15Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 659.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedBotonWidget6(),
              )
            ]),
      ),
    ));
  }
}
