import 'package:flutter/material.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/GeneratedFechaWidget.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/GeneratedVector2Widget.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/GeneratedVector1Widget.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/GeneratedEllipse9Widget.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/GeneratedEllipse12Widget.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/GeneratedVistasWidget.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/GeneratedEllipse10Widget.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/GeneratedEllipse11Widget.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/GeneratedGraficaWidget.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/GeneratedGroup8Widget.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/GeneratedEllipse8Widget.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/Generated25Widget.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/GeneratedVectorWidget180.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/GeneratedMensajesWidget.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/GeneratedGroup10Widget.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/GeneratedComprasenlosultimos6aosWidget.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/GeneratedStatsWidget.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/GeneratedMenusuoeriorWidget2.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/Generated1589Widget.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/GeneratedMenuinferiorWidget5.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/GeneratedVistasdepropiedadesWidget.dart';
import 'package:flutterapp/optica2020app/generatedfavoritoswidget10/generated/GeneratedCitasWidget.dart';

/* Frame Favoritos
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFavoritosWidget10 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 240, 240, 240),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 806.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 90.0,
                child: GeneratedMenuinferiorWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.04906400966183575;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 20.3125;

                  double percentHeight = 0.026157924107142856;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 23.4375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8623188405797102,
                        translateY: constraints.maxHeight * 0.9330357142857143,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget180())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 110.0,
                child: GeneratedMenusuoeriorWidget2(),
              ),
              Positioned(
                left: 17.0,
                top: 133.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 80.0,
                child: GeneratedStatsWidget(),
              ),
              Positioned(
                left: 17.0,
                top: 236.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 80.0,
                child: GeneratedVistasWidget(),
              ),
              Positioned(
                left: 216.0,
                top: 133.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 80.0,
                child: GeneratedMensajesWidget(),
              ),
              Positioned(
                left: 216.0,
                top: 236.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 80.0,
                child: GeneratedCitasWidget(),
              ),
              Positioned(
                left: 17.0,
                top: 339.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 380.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 348.0,
                right: null,
                bottom: null,
                width: 237.0,
                height: 43.0,
                child: GeneratedVistasdepropiedadesWidget(),
              ),
              Positioned(
                left: 35.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 31.0,
                child: Generated1589Widget(),
              ),
              Positioned(
                left: 35.0,
                top: 424.0,
                right: null,
                bottom: null,
                width: 172.0,
                height: 16.0,
                child: GeneratedComprasenlosultimos6aosWidget(),
              ),
              Positioned(
                left: 112.0,
                top: 404.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 19.0,
                child: Generated25Widget(),
              ),
              Positioned(
                left: 259.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 30.0,
                child: GeneratedFechaWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 482.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 200.0,
                child: GeneratedGraficaWidget(),
              ),
              Positioned(
                left: 32.5,
                top: 500.1322021484375,
                right: null,
                bottom: null,
                width: 348.0,
                height: 145.36778259277344,
                child: GeneratedVector1Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 348.0,
                height: 181.0,
                child: GeneratedVector2Widget(),
              ),
              Positioned(
                left: 97.0,
                top: 566.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 14.0,
                child: GeneratedEllipse8Widget(),
              ),
              Positioned(
                left: 158.0,
                top: 575.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 14.0,
                child: GeneratedEllipse9Widget(),
              ),
              Positioned(
                left: 219.0,
                top: 591.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 14.0,
                child: GeneratedEllipse10Widget(),
              ),
              Positioned(
                left: 280.0,
                top: 552.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 14.0,
                child: GeneratedEllipse11Widget(),
              ),
              Positioned(
                left: 331.0,
                top: 504.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 14.0,
                child: GeneratedEllipse12Widget(),
              ),
              Positioned(
                left: 80.0,
                top: 524.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 33.87334442138672,
                child: GeneratedGroup6Widget(),
              ),
              Positioned(
                left: 141.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 33.87334442138672,
                child: GeneratedGroup7Widget(),
              ),
              Positioned(
                left: 314.0,
                top: 466.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 33.87334442138672,
                child: GeneratedGroup10Widget(),
              ),
              Positioned(
                left: 263.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 33.87334442138672,
                child: GeneratedGroup9Widget(),
              ),
              Positioned(
                left: 202.0,
                top: 550.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 33.87334442138672,
                child: GeneratedGroup8Widget(),
              )
            ]),
      ),
    ));
  }
}
