import 'package:flutter/material.dart';
import 'package:flutterapp/optica2020app/generatediniciowidget1/generated/Generated0GfPlommtxMWidget.dart';
import 'package:flutterapp/optica2020app/generatediniciowidget1/generated/Generated10productosencontradosWidget.dart';
import 'package:flutterapp/optica2020app/generatediniciowidget1/generated/GeneratedMenuinferiorWidget1.dart';
import 'package:flutterapp/optica2020app/generatediniciowidget1/generated/GeneratedFrame5Widget.dart';
import 'package:flutterapp/optica2020app/generatediniciowidget1/generated/GeneratedBuscadorWidget.dart';
import 'package:flutterapp/optica2020app/generatediniciowidget1/generated/GeneratedMenusuoeriorWidget.dart';

/* Frame Inicio
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInicioWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 240, 240, 240),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 806.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 90.0,
                child: GeneratedMenuinferiorWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 110.0,
                child: GeneratedMenusuoeriorWidget(),
              ),
              Positioned(
                left: 17.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 60.0,
                child: GeneratedBuscadorWidget(),
              ),
              Positioned(
                left: 17.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 16.0,
                child: Generated10productosencontradosWidget(),
              ),
              Positioned(
                left: -2624.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 1540.0,
                height: 952.0,
                child: Generated0GfPlommtxMWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 298.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 425.0,
                child: GeneratedFrame5Widget(),
              )
            ]),
      ),
    ));
  }
}
