import 'package:flutter/material.dart';
import 'package:flutterapp/optica2020app/generatedmenusuperiorwidget2/generated/GeneratedArrowbackcircleWidget2.dart';

/* Component Menu superior
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMenusuperiorWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 110.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 20.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedArrowbackcircleWidget2(),
              )
            ]),
      ),
    ));
  }
}
