import 'package:flutter/material.dart';
import 'package:flutterapp/optica2020app/generatedportadawidget1/generated/GeneratedCheckmarkcircleWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/optica2020app/generatedportadawidget1/generated/GeneratedMaskGroupWidget2.dart';
import 'package:flutterapp/optica2020app/generatedportadawidget1/generated/GeneratedMOM0aPcKWhQWidget1.dart';

/* Component Portada
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPortadaWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 391.0,
      height: 449.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.only(
          topLeft: Radius.circular(20.0),
          topRight: Radius.circular(20.0),
          bottomRight: Radius.circular(0.0),
          bottomLeft: Radius.circular(0.0),
        ),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height =
                    constraints.maxHeight * 0.35634743875278396;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedMOM0aPcKWhQWidget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.26854219948849106;

                final double height =
                    constraints.maxHeight * 0.23385300668151449;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.03836317135549872,
                      y: constraints.maxHeight * 0.2383073496659243,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedMaskGroupWidget2(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 1016.0,
              top: 2032.0,
              right: null,
              bottom: null,
              width: 25.0,
              height: 25.0,
              child: GeneratedCheckmarkcircleWidget1(),
            )
          ]),
    ));
  }
}
