import 'package:flutter/material.dart';
import 'package:flutterapp/optica2020app/generatedcrearpublicacionwidget/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/optica2020app/generatedcrearpublicacionwidget/generated/GeneratedEstasaunospasosdellegaramilesdeperosonasWidget.dart';
import 'package:flutterapp/optica2020app/generatedcrearpublicacionwidget/generated/GeneratedMenusuoeriorWidget1.dart';
import 'package:flutterapp/optica2020app/generatedcrearpublicacionwidget/generated/GeneratedPublicatureseaahoraWidget.dart';
import 'package:flutterapp/optica2020app/generatedcrearpublicacionwidget/generated/GeneratedMenuinferiorWidget2.dart';
import 'package:flutterapp/optica2020app/generatedcrearpublicacionwidget/generated/GeneratedSpecsamicoWidget.dart';
import 'package:flutterapp/optica2020app/generatedcrearpublicacionwidget/generated/GeneratedBotonWidget2.dart';

/* Frame Crear publicacion
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCrearpublicacionWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 240, 240, 240),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 806.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 90.0,
                child: GeneratedMenuinferiorWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 110.0,
                child: GeneratedMenusuoeriorWidget1(),
              ),
              Positioned(
                left: 17.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 380.0,
                height: 640.0,
                child: GeneratedRectangle20Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.893719806763285;

                  final double height =
                      constraints.maxHeight * 0.42091325351170134;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.05314009661835749,
                        y: constraints.maxHeight * 0.29910714285714285,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedSpecsamicoWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 81.0,
                top: 169.0,
                right: null,
                bottom: null,
                width: 252.0,
                height: 28.0,
                child: GeneratedPublicatureseaahoraWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 169.0,
                right: null,
                bottom: null,
                width: 353.0,
                height: 107.0,
                child:
                    GeneratedEstasaunospasosdellegaramilesdeperosonasWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 678.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedBotonWidget2(),
              )
            ]),
      ),
    ));
  }
}
