import 'package:flutter/material.dart';
import 'package:flutterapp/optica2020app/generatedmenuinferiorwidget/generated/GeneratedVectorWidget12.dart';
import 'package:flutterapp/optica2020app/generatedmenuinferiorwidget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/optica2020app/generatedmenuinferiorwidget/generated/GeneratedPerfilWidget.dart';
import 'package:flutterapp/optica2020app/generatedmenuinferiorwidget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/optica2020app/generatedmenuinferiorwidget/generated/GeneratedFavoritosWidget.dart';
import 'package:flutterapp/optica2020app/generatedmenuinferiorwidget/generated/GeneratedHomeWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/optica2020app/generatedmenuinferiorwidget/generated/GeneratedAjustesWidget.dart';

/* Component Menu inferior
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMenuinferiorWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 414.0,
      height: 90.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 240, 240, 240),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 15.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 75.0,
              child: GeneratedRectangle4Widget(),
            ),
            Positioned(
              left: 169.0,
              top: -24.0,
              right: null,
              bottom: null,
              width: 70.0,
              height: 70.0,
              child: GeneratedEllipse1Widget(),
            ),
            Positioned(
              left: 266.0,
              top: 33.0,
              right: null,
              bottom: null,
              width: 42.0,
              height: 40.0,
              child: GeneratedAjustesWidget(),
            ),
            Positioned(
              left: 22.0,
              top: 33.0,
              right: null,
              bottom: null,
              width: 31.0,
              height: 40.0,
              child: GeneratedHomeWidget(),
            ),
            Positioned(
              left: 107.0,
              top: 33.0,
              right: null,
              bottom: null,
              width: 29.0,
              height: 40.0,
              child: GeneratedPerfilWidget(),
            ),
            Positioned(
              left: 342.0,
              top: 33.0,
              right: null,
              bottom: null,
              width: 51.0,
              height: 40.0,
              child: GeneratedFavoritosWidget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.12077294685990338;
                double scaleX = (constraints.maxWidth * percentWidth) / 50.0;

                double percentHeight = 0.5555555555555556;
                double scaleY = (constraints.maxHeight * percentHeight) / 50.0;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.4323671497584541,
                      translateY: constraints.maxHeight * -0.15555555555555556,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget12())
                ]);
              }),
            )
          ]),
    ));
  }
}
